---
- name: Install required packages
  when:
    - alertmanager_oauth2_static_users | length > 0
  loop:
    - python3-passlib
    - python3-bcrypt
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - alertmanager
    - oauth2

- name: Check existing install
  when:
    - alertmanager_installation == 'native'
  register: alertmanager_oauth2_version_check
  failed_when: false
  changed_when: false
  check_mode: false
  ansible.builtin.shell: /usr/bin/alertmanager-oauth2 --version 2>&1
  tags:
    - alertmanager
    - oauth2

- name: Fact version change
  when:
    - alertmanager_installation == 'native'
  ansible.builtin.set_fact:
    alertmanager_oauth2_version_changed: "{{ alertmanager_oauth2_version_check.rc != 0 or (alertmanager_oauth2_version_check.stdout_lines is defined and alertmanager_oauth2_version not in alertmanager_oauth2_version_check.stdout_lines[0]) | bool }}"
  tags:
    - alertmanager
    - oauth2

- name: Download release tarball
  when:
    - alertmanager_installation == 'native'
    - alertmanager_oauth2_version_changed
  ansible.builtin.unarchive:
    src: "{{ alertmanager_oauth2_download }}"
    dest: /usr/local/src
    remote_src: true
    owner: root
    group: root
  tags:
    - alertmanager
    - oauth2

- name: Copy oauth2 binary
  when:
    - alertmanager_installation == 'native'
    - alertmanager_oauth2_version_changed
    - not ansible_check_mode
  notify:
    - Restart alertmanager-oauth2
  ansible.builtin.copy:
    src: "/usr/local/src/oauth2-proxy-v{{ alertmanager_oauth2_version }}.linux-{{ alertmanager_oauth2_arch }}/oauth2-proxy"
    dest: /usr/bin/alertmanager-oauth2
    remote_src: true
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - alertmanager
    - oauth2

- name: Write users config
  when:
    - alertmanager_oauth2_static_users | length > 0
  loop: "{{ alertmanager_oauth2_static_users }}"
  loop_control:
    label: "{{ item.username }}"
  notify:
    - Restart alertmanager-oauth2
  community.general.htpasswd:
    path: /etc/alertmanager/htpasswd
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    crypt_scheme: bcrypt
    owner: "{{ 'alertmanager' if alertmanager_installation == 'native' else 'nobody' }}"
    group: "{{ 'alertmanager' if alertmanager_installation == 'native' else 'nogroup' }}"
    mode: "{{ 'u=rw,g=r,o=' if alertmanager_installation == 'native' else 'u=rw,g=r,o=r' }}"
    state: "{{ item.state | default('present') }}"
  tags:
    - alertmanager
    - oauth2

- name: Write default config
  notify:
    - Restart alertmanager-oauth2
  ansible.builtin.template:
    src: oauth2/default.j2
    dest: /etc/default/alertmanager-oauth2
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - alertmanager
    - oauth2

- name: Write service file
  notify:
    - Restart alertmanager-oauth2
  ansible.builtin.template:
    src: oauth2/service.j2
    dest: /etc/systemd/system/alertmanager-oauth2.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - alertmanager
    - oauth2

- name: Pull docker image
  when:
    - alertmanager_installation == 'docker'
    - alertmanager_oauth2_pull_image
  community.docker.docker_image:
    name: "{{ alertmanager_oauth2_image }}"
    source: pull
  tags:
    - alertmanager
    - oauth2

- name: Create docker network
  when:
    - alertmanager_installation == 'docker'
    - false if alertmanager_oauth2_network is none else (alertmanager_oauth2_network | length > 0)
  community.docker.docker_network:
    name: '{{ alertmanager_oauth2_network }}'
  tags:
    - alertmanager
    - oauth2

- name: Start alertmanager-oauth2 service
  ansible.builtin.systemd:
    name: alertmanager-oauth2
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - alertmanager
    - oauth2

- name: Remove install directory
  when:
    - alertmanager_installation == 'native'
  ansible.builtin.file:
    path: "/usr/local/src/oauth2-proxy-v{{ alertmanager_oauth2_version }}.linux-{{ alertmanager_oauth2_arch }}"
    state: absent
  tags:
    - alertmanager
    - oauth2

...
